package de.greenrobot.daoMyFun;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DIAN_PING_DATA.
 */
public class DianPingData {

    private Long id;
    private String type;
    private String data;
    private java.util.Date update_time;

    public DianPingData() {
    }

    public DianPingData(Long id) {
        this.id = id;
    }

    public DianPingData(Long id, String type, String data, java.util.Date update_time) {
        this.id = id;
        this.type = type;
        this.data = data;
        this.update_time = update_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public java.util.Date getUpdate_time() {
        return update_time;
    }

    public void setUpdate_time(java.util.Date update_time) {
        this.update_time = update_time;
    }

}
