package de.greenrobot.daoMyFun;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TRIBE__RELATIONSHIP.
 */
public class Tribe_Relationship {

    private Long id;
    /** Not-null value. */
    private String normal_id;
    /** Not-null value. */
    private String hx_id;
    /** Not-null value. */
    private String present_name;
    private boolean is_group;
    private String image_path;
    private long location;

    public Tribe_Relationship() {
    }

    public Tribe_Relationship(Long id) {
        this.id = id;
    }

    public Tribe_Relationship(Long id, String normal_id, String hx_id, String present_name, boolean is_group, String image_path, long location) {
        this.id = id;
        this.normal_id = normal_id;
        this.hx_id = hx_id;
        this.present_name = present_name;
        this.is_group = is_group;
        this.image_path = image_path;
        this.location = location;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNormal_id() {
        return normal_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNormal_id(String normal_id) {
        this.normal_id = normal_id;
    }

    /** Not-null value. */
    public String getHx_id() {
        return hx_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHx_id(String hx_id) {
        this.hx_id = hx_id;
    }

    /** Not-null value. */
    public String getPresent_name() {
        return present_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPresent_name(String present_name) {
        this.present_name = present_name;
    }

    public boolean getIs_group() {
        return is_group;
    }

    public void setIs_group(boolean is_group) {
        this.is_group = is_group;
    }

    public String getImage_path() {
        return image_path;
    }

    public void setImage_path(String image_path) {
        this.image_path = image_path;
    }

    public long getLocation() {
        return location;
    }

    public void setLocation(long location) {
        this.location = location;
    }

}
