package de.greenrobot.daoMyFun;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONVERSATION_TRIBE.
 */
public class Conversation_tribe {

    private Long id;
    private String con_id;
    private String user_id;
    private String image;
    private String group_id;
    private Integer status;
    private Long time;
    private Integer type;

    public Conversation_tribe() {
    }

    public Conversation_tribe(Long id) {
        this.id = id;
    }

    public Conversation_tribe(Long id, String con_id, String user_id, String image, String group_id, Integer status, Long time, Integer type) {
        this.id = id;
        this.con_id = con_id;
        this.user_id = user_id;
        this.image = image;
        this.group_id = group_id;
        this.status = status;
        this.time = time;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCon_id() {
        return con_id;
    }

    public void setCon_id(String con_id) {
        this.con_id = con_id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getGroup_id() {
        return group_id;
    }

    public void setGroup_id(String group_id) {
        this.group_id = group_id;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

}
