package de.greenrobot.daoMyFun;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONVERSATION_MSG.
 */
public class Conversation_msg {

    private Long id;
    private String con_id;
    private String msg_id;
    private String user_id;
    private String group_id;
    private Integer status;
    private Long time;

    public Conversation_msg() {
    }

    public Conversation_msg(Long id) {
        this.id = id;
    }

    public Conversation_msg(Long id, String con_id, String msg_id, String user_id, String group_id, Integer status, Long time) {
        this.id = id;
        this.con_id = con_id;
        this.msg_id = msg_id;
        this.user_id = user_id;
        this.group_id = group_id;
        this.status = status;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCon_id() {
        return con_id;
    }

    public void setCon_id(String con_id) {
        this.con_id = con_id;
    }

    public String getMsg_id() {
        return msg_id;
    }

    public void setMsg_id(String msg_id) {
        this.msg_id = msg_id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getGroup_id() {
        return group_id;
    }

    public void setGroup_id(String group_id) {
        this.group_id = group_id;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

}
