package de.greenrobot.daoMyFun;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.daoMyFun.Tribe_Relationship;
import de.greenrobot.daoMyFun.Conversation_tribe;
import de.greenrobot.daoMyFun.Conversation_msg;
import de.greenrobot.daoMyFun.DianPingData;

import de.greenrobot.daoMyFun.Tribe_RelationshipDao;
import de.greenrobot.daoMyFun.Conversation_tribeDao;
import de.greenrobot.daoMyFun.Conversation_msgDao;
import de.greenrobot.daoMyFun.DianPingDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tribe_RelationshipDaoConfig;
    private final DaoConfig conversation_tribeDaoConfig;
    private final DaoConfig conversation_msgDaoConfig;
    private final DaoConfig dianPingDataDaoConfig;

    private final Tribe_RelationshipDao tribe_RelationshipDao;
    private final Conversation_tribeDao conversation_tribeDao;
    private final Conversation_msgDao conversation_msgDao;
    private final DianPingDataDao dianPingDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tribe_RelationshipDaoConfig = daoConfigMap.get(Tribe_RelationshipDao.class).clone();
        tribe_RelationshipDaoConfig.initIdentityScope(type);

        conversation_tribeDaoConfig = daoConfigMap.get(Conversation_tribeDao.class).clone();
        conversation_tribeDaoConfig.initIdentityScope(type);

        conversation_msgDaoConfig = daoConfigMap.get(Conversation_msgDao.class).clone();
        conversation_msgDaoConfig.initIdentityScope(type);

        dianPingDataDaoConfig = daoConfigMap.get(DianPingDataDao.class).clone();
        dianPingDataDaoConfig.initIdentityScope(type);

        tribe_RelationshipDao = new Tribe_RelationshipDao(tribe_RelationshipDaoConfig, this);
        conversation_tribeDao = new Conversation_tribeDao(conversation_tribeDaoConfig, this);
        conversation_msgDao = new Conversation_msgDao(conversation_msgDaoConfig, this);
        dianPingDataDao = new DianPingDataDao(dianPingDataDaoConfig, this);

        registerDao(Tribe_Relationship.class, tribe_RelationshipDao);
        registerDao(Conversation_tribe.class, conversation_tribeDao);
        registerDao(Conversation_msg.class, conversation_msgDao);
        registerDao(DianPingData.class, dianPingDataDao);
    }
    
    public void clear() {
        tribe_RelationshipDaoConfig.getIdentityScope().clear();
        conversation_tribeDaoConfig.getIdentityScope().clear();
        conversation_msgDaoConfig.getIdentityScope().clear();
        dianPingDataDaoConfig.getIdentityScope().clear();
    }

    public Tribe_RelationshipDao getTribe_RelationshipDao() {
        return tribe_RelationshipDao;
    }

    public Conversation_tribeDao getConversation_tribeDao() {
        return conversation_tribeDao;
    }

    public Conversation_msgDao getConversation_msgDao() {
        return conversation_msgDao;
    }

    public DianPingDataDao getDianPingDataDao() {
        return dianPingDataDao;
    }

}
